[pytest]
pythonpath = src test
filterwarnings =
    ignore:'audioop' is deprecated and slated for removal in Python 3.13:DeprecationWarning:pydub.utils
    ignore:Call to deprecated method findAll.*:DeprecationWarning:readabilipy.simplifiers.html
