from collections.abc import Mapping
from typing import Protocol


class S3Client(Protocol):

    def head_bucket(self, Bucket: str) -> object: ...

    def create_bucket(self, Bucket: str) -> object: ...

    def put_object(self, **kwargs: object) -> object: ...

    def upload_file(self, **kwargs: object) -> object: ...

    def get_object(self, Bucket: str, Key: str) -> Mapping[str, object]: ...

    def delete_object(self, Bucket: str, Key: str) -> object: ...
