"""token_cost_configurations

Revision ID: 233cbdadb4b6
Revises: a5d60e76f435
Create Date: 2026-05-22 01:04:08.200051

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "233cbdadb4b6"
down_revision: Union[str, None] = "a5d60e76f435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_memberships",
        sa.Column("max_output_tokens", sa.Integer(), server_default = sa.text("3500"), nullable = False),
    )
    op.add_column(
        "chat_memberships",
        sa.Column("max_chat_history_depth", sa.Integer(), server_default = sa.text("30"), nullable = False),
    )
    op.add_column(
        "chat_memberships",
        sa.Column("max_iterations", sa.Integer(), server_default = sa.text("20"), nullable = False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_memberships", "max_iterations")
    op.drop_column("chat_memberships", "max_chat_history_depth")
    op.drop_column("chat_memberships", "max_output_tokens")
    # ### end Alembic commands ###
