"""message_delivery_fees

Revision ID: 250e8786269e
Revises: c731e1e75917
Create Date: 2026-10-09 10:52:50.897691

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "250e8786269e"
down_revision: Union[str, None] = "c731e1e75917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # backfill pre-delivery records as reconciled during the migration
    op.add_column("usage_records", sa.Column("is_delivery_reconciled", sa.Boolean(), server_default = "true", nullable = False))
    # but then default new records to pending reconciliation
    op.alter_column("usage_records", "is_delivery_reconciled", server_default = "false")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "is_delivery_reconciled")
    # ### end Alembic commands ###
