"""stock_quote_feature

Revision ID: 5acf7f96c138
Revises: 2c3d61b37410
Create Date: 2026-07-24 17:33:16.312504

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import BYTEA

# revision identifiers, used by Alembic.
revision: str = "5acf7f96c138"
down_revision: Union[str, None] = "2c3d61b37410"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("twelve_data_api_key", BYTEA, nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_api_stock_quote", sa.String(), nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "tool_choice_api_stock_quote")
    op.drop_column("simulants", "twelve_data_api_key")
    # ### end Alembic commands ###
