"""attachment_url_simplification

Revision ID: 6faaf160de6e
Revises: e6bb7bc081fc
Create Date: 2026-07-09 22:00:28.222288

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6faaf160de6e"
down_revision: Union[str, None] = "e6bb7bc081fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message_attachments", "last_url_until")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message_attachments", sa.Column("last_url_until", sa.INTEGER(), autoincrement = False, nullable = True))
    # ### end Alembic commands ###
