"""burst_message_queues

Revision ID: c731e1e75917
Revises: a5fee1e83958
Create Date: 2026-09-10 15:29:52.204294

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c731e1e75917"
down_revision: Union[str, None] = "a5fee1e83958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("chat_message_bursts",
        sa.Column("chat_id", sa.UUID(), nullable = False),
        sa.Column("author_id", sa.UUID(), nullable = False),
        sa.Column("message_count", sa.BigInteger(), nullable = False),
        sa.Column("process_after", sa.DateTime(), nullable = False),
        sa.Column("last_message_sent_at", sa.DateTime(), nullable = False),
        sa.Column("last_message_ingestion_order", sa.BigInteger(), nullable = False),
        sa.Column("is_addressed", sa.Boolean(), nullable = False),
        sa.Column("is_processing", sa.Boolean(), nullable = False),
        sa.ForeignKeyConstraint(["author_id"], ["simulants.id"], name = "chat_message_bursts_author_id_fkey", ondelete = "CASCADE"),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_configs.chat_id"], name = "chat_message_bursts_chat_id_fkey", ondelete = "CASCADE"),
        sa.PrimaryKeyConstraint("chat_id", "author_id", name = "pk_chat_message_burst"),
    )
    op.add_column("chat_messages", sa.Column("ingestion_order", sa.BigInteger(), sa.Identity(always = False), nullable = False))
    op.create_unique_constraint("uq_chat_messages_ingestion_order", "chat_messages", ["ingestion_order"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_chat_messages_ingestion_order", "chat_messages", type_ = "unique")
    op.drop_column("chat_messages", "ingestion_order")
    op.drop_table("chat_message_bursts")
    # ### end Alembic commands ###
