"""video_generation

Revision ID: d938153994a8
Revises: 32b3ae52bbdf
Create Date: 2026-07-26 22:25:12.918713

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d938153994a8"
down_revision: Union[str, None] = "32b3ae52bbdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("tool_choice_videos_gen", sa.String(), nullable = True))
    op.add_column("usage_records", sa.Column("output_video_size", sa.String(), nullable = True))
    op.add_column("usage_records", sa.Column("output_video_duration_seconds", sa.Float(), nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "output_video_duration_seconds")
    op.drop_column("usage_records", "output_video_size")
    op.drop_column("simulants", "tool_choice_videos_gen")
    # ### end Alembic commands ###
